# Generated by Django 2.1.2 on 2018-10-15 12:06

from django.db import migrations, models
import pizza.helper


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pizza',
            name='secretKey',
            field=models.CharField(default=pizza.helper.secret, editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.IntegerField(),
        ),
    ]
